services:
  # db
  mongo:
    image: mongo:7.0.16
    volumes:
      - ./mongo-backup/:/dump/
      - ./mongo-init/init-ecommerce.js:/docker-entrypoint-initdb.d/init-ecommerce.js
    ports:
      - 20001:27017
    env_file:
      - .env

  # simple UI for viewing mongo
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 20002:8081
    env_file:
      - .env
    depends_on:
      - mongo

  # backend:
  #   image: imppack/backend:0.0.3
  #   # command: /bin/sh -c "while :; do sleep 1; done"
  #   build: backend/
  #   volumes:
  #     - ./backend-data:/backend/uploads/
  #   #   - ./backend:/backend
  #   ports:
  #     - 10001:4000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo

  # admin:
  #   image: imppack/admin:0.0.3
  #   build: admin/
  #   ports:
  #     - 10002:5174
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend
  #     - mongo

  # frontend:
  #   image: imppack/frontend:0.0.3
  #   build: frontend/
  #   ports:
  #     - 10003:5173
  #   env_file:
  #     - .env
  #   depends_on:
  #     - admin
  #     - backend
  #     - mongo

 